checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php: '5.5.0'
    dependencies:
        before:
            - mysql -uroot -e "create database IF NOT EXISTS client_not;"
            - mysql -uroot -e "CREATE USER 'client_not'@'localhost' IDENTIFIED BY 'zhhnqBF26wtnUnP9';"
            - mysql -uroot -e "GRANT ALL ON client_not.* TO 'client_not'@'localhost';"
            - mysql -uroot client_not < tests/clientNotifications.sql
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

